use_frameworks!
inhibit_all_warnings!

platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'DynamicAndStaticLibTestDemo' do
  pod 'DynamicAndStaticLibTest', :path => '../'

end

pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
