use_frameworks!
#source 'https://github.com/JJCSoftDeveloper/libwebp.git'

target 'DynamicAndStaticLib_Example' do
  pod 'libwebp',:git => 'https://github.com/JJCSoftDeveloper/libwebp.git'
  pod 'DynamicAndStaticLib', :path => '../'
  
end

pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

